apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter
  namespace: observability
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/component: node-exporter
automountServiceAccountToken: false
