apiVersion: v1
kind: LimitRange
metadata:
  name: observability-limits
  namespace: observability
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      max:
        cpu: "4"
        memory: 8Gi
