{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability.nodeExporter.fullname" . }}
  namespace: {{ include "observability.namespace" . }}
  labels:
    {{- include "observability.nodeExporter.labels" . | nindent 4 }}
  {{- with .Values.nodeExporter.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nodeExporter.service.type }}
  clusterIP: {{ .Values.nodeExporter.service.clusterIP }}
  ports:
    - name: metrics
      port: {{ .Values.nodeExporter.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "observability.nodeExporter.selectorLabels" . | nindent 4 }}
{{- end }}
