apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: observability
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: grafana
automountServiceAccountToken: false
