{{- if and .Values.grafana.enabled .Values.grafana.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "observability.grafana.fullname" .) .Values.grafana.serviceAccount.name }}
  namespace: {{ include "observability.namespace" . }}
  labels:
    {{- include "observability.grafana.labels" . | nindent 4 }}
  {{- with .Values.grafana.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
